# Generated by Django 5.1 on 2025-10-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0003_alter_companyprofile_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='branch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
