# Generated by Django 5.1.2 on 2026-01-21 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0005_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval status'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False, help_text='Whether all required fields are filled'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
