# Generated by Django 5.1.2 on 2026-01-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0006_companyprofile_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Admin approval status'),
        ),
    ]
