# Generated by Django 5.1.2 on 2026-07-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0007_alter_companyprofile_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval status'),
        ),
    ]
