# Generated by Django 5.1.2 on 2026-08-11 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0008_alter_companyprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='is_rejected',
            field=models.BooleanField(default=False, help_text='Whether the profile is currently in a rejected state'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Latest reason provided by admin for rejection', null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='resubmitted_at',
            field=models.DateTimeField(blank=True, help_text='When the refurbisher last requested a re-review', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Admin approval status'),
        ),
        migrations.CreateModel(
            name='ApprovalReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('rejected', 'Rejected'), ('approved', 'Approved'), ('resubmitted', 'Resubmitted')], max_length=15)),
                ('reason', models.TextField(blank=True, help_text="Admin's rejection reason, or refurbisher's reply message", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='UserDetail.companyprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_logs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
