# Generated by Django 5.1.2 on 2026-08-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0009_companyprofile_is_rejected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval status'),
        ),
    ]
