# Generated by Django 5.1.2 on 2026-09-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0010_alter_companyprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='shiprocket_pickup_code',
            field=models.CharField(blank=True, help_text="ShipRocket 'pickup_location' nickname used as this refurbisher's warehouse", max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='shiprocket_warehouse_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='shiprocket_warehouse_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='shiprocket_warehouse_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='shiprocket_warehouse_response',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
