# Generated by Django 5.1.2 on 2026-10-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0011_companyprofile_shiprocket_pickup_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
