# Generated by Django 5.1.2 on 2026-07-28 10:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/categories/')),
                ('link_url', models.CharField(max_length=200)),
                ('badge_text', models.CharField(blank=True, max_length=60)),
                ('badge_style', models.CharField(choices=[('bg-dark', 'Dark'), ('bg-success', 'Green')], default='bg-dark', max_length=30)),
                ('product_count', models.CharField(blank=True, help_text='e.g. "450+"', max_length=30)),
                ('starting_price', models.CharField(blank=True, help_text='e.g. "₹12,999"', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category Card',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroBannerSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('bg_style', models.CharField(choices=[('rc-slide-dark', 'Dark (black)'), ('rc-slide-light', 'Light (white)'), ('rc-slide-green', 'Green'), ('rc-slide-repair', 'Repair (dark + green text)')], default='rc-slide-dark', max_length=30)),
                ('tag_text', models.CharField(blank=True, max_length=80)),
                ('tag_style', models.CharField(choices=[('tag-green', 'Green'), ('tag-dark', 'Dark'), ('tag-light', 'Light')], default='tag-green', max_length=30)),
                ('heading', models.CharField(max_length=200)),
                ('body_text', models.TextField(blank=True)),
                ('btn1_text', models.CharField(blank=True, max_length=60)),
                ('btn1_url', models.CharField(blank=True, max_length=200)),
                ('btn1_style', models.CharField(default='btn rc-btn-primary', max_length=60)),
                ('btn2_text', models.CharField(blank=True, max_length=60)),
                ('btn2_url', models.CharField(blank=True, max_length=200)),
                ('btn2_style', models.CharField(default='btn rc-btn-text', max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/hero/')),
                ('image_max_width', models.CharField(blank=True, help_text='e.g. 500px or fit-content', max_length=20)),
                ('badge_top_right', models.CharField(blank=True, max_length=80)),
                ('badge_bottom_center', models.CharField(blank=True, max_length=80)),
                ('badge_circle', models.CharField(blank=True, help_text='Circular badge text (e.g. "Up to 70% OFF")', max_length=80)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavCategoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('url', models.CharField(max_length=200)),
                ('highlight_class', models.CharField(blank=True, choices=[('', 'Normal'), ('highlight-red', 'Red'), ('highlight-blue', 'Blue')], max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nav Category Link',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PartnerCTABanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('subtext', models.CharField(max_length=200)),
                ('btn_text', models.CharField(default='Apply Now', max_length=60)),
                ('btn_url', models.CharField(default='/partner-application', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Partner CTA Banner',
            },
        ),
        migrations.CreateModel(
            name='PriceRangeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(help_text='e.g. ENTRY LEVEL', max_length=30)),
                ('label', models.CharField(help_text='e.g. Under ₹20K', max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('link_text', models.CharField(default='Browse →', max_length=60)),
                ('link_url', models.CharField(max_length=200)),
                ('is_dark', models.BooleanField(default=False, help_text='Dark card style')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Price Range Card',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('section_type', models.CharField(choices=[('hot_deals', 'Hot Deals'), ('end_of_year', 'End of Year Sale'), ('recommended', 'Recommended for You'), ('featured', 'Recarvit Featured'), ('certified_iphones', 'Certified Renewed iPhones'), ('certified_samsung', 'Certified Renewed Samsung')], max_length=30, unique=True)),
                ('bg_style', models.CharField(blank=True, choices=[('', 'White'), ('bg-off-white', 'Off White'), ('bg-soft-green', 'Soft Green')], max_length=30)),
                ('see_all_url', models.CharField(blank=True, max_length=200)),
                ('see_all_text', models.CharField(default='See all', max_length=60)),
                ('show_timer', models.BooleanField(default=False, help_text='Show countdown timer (Hot Deals)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('promo_badge', models.CharField(blank=True, max_length=60)),
                ('promo_heading', models.CharField(blank=True, max_length=120)),
                ('promo_btn_text', models.CharField(blank=True, max_length=60)),
                ('promo_btn_url', models.CharField(blank=True, max_length=200)),
                ('promo_image', models.ImageField(blank=True, null=True, upload_to='homepage/sections/')),
                ('promo_style', models.CharField(blank=True, help_text='iphones-promo or samsung-promo', max_length=30)),
            ],
            options={
                'verbose_name': 'Product Section',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Promo Banner',
            },
        ),
        migrations.CreateModel(
            name='RenewedBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Recarvit Certified: As Good As New.', max_length=200)),
                ('subtext', models.CharField(default="We test 50+ checkpoints (Battery, Screen, Camera) so you don't have to.", max_length=200)),
                ('cta_text', models.CharField(default='See the Checklist', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Renewed Banner',
            },
        ),
        migrations.CreateModel(
            name='ShopByPriceSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/sbp/')),
                ('label_line1', models.CharField(help_text='e.g. Under', max_length=20)),
                ('label_line2', models.CharField(help_text='e.g. ₹6,999', max_length=20)),
                ('link_url', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shop By Price Slide',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SpotlightProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('brand_label', models.CharField(max_length=60)),
                ('product_model_id', models.PositiveIntegerField(help_text='ProductModel.id')),
                ('display_name', models.CharField(max_length=200)),
                ('display_image', models.ImageField(blank=True, null=True, upload_to='homepage/spotlight/')),
                ('specs', models.JSONField(default=list, help_text='List of spec pill strings, e.g. ["CORE I7","16GB"]')),
                ('price', models.CharField(help_text='e.g. ₹ 41,999', max_length=30)),
                ('original_price', models.CharField(max_length=30)),
                ('discount_pct', models.PositiveIntegerField(default=0, help_text='e.g. 43')),
                ('save_amount', models.CharField(blank=True, help_text='e.g. ₹32,001', max_length=30)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('available_count', models.PositiveIntegerField(default=0)),
                ('link_url', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Spotlight Product',
            },
        ),
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.FloatField(help_text='Numeric target for counter animation')),
                ('decimals', models.PositiveSmallIntegerField(default=0)),
                ('suffix', models.CharField(blank=True, help_text='e.g. + or %', max_length=10)),
                ('label', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Stat Counter',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestimonialCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=80)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('product_bought', models.CharField(max_length=120)),
                ('product_icon', models.CharField(default='fas fa-mobile-alt', max_length=60)),
                ('review_text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrustStripItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fas fa-check-circle', help_text='FontAwesome class', max_length=80)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trust Strip Item',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_model_id', models.PositiveIntegerField(help_text='ProductModel.id from Product app')),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('display_image', models.ImageField(blank=True, null=True, upload_to='homepage/items/')),
                ('badge_text', models.CharField(blank=True, help_text='e.g. -54%', max_length=30)),
                ('badge_style', models.CharField(blank=True, help_text='inline style for badge bg/color', max_length=80)),
                ('specs_text', models.CharField(blank=True, help_text='e.g. 128GB | 6GB RAM', max_length=100)),
                ('display_price', models.CharField(blank=True, help_text='Overrides live price', max_length=30)),
                ('original_price', models.CharField(blank=True, max_length=30)),
                ('link_url', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Admin.productsection')),
            ],
            options={
                'verbose_name': 'Product Section Item',
                'ordering': ['order'],
            },
        ),
    ]
