# Generated by Django 5.1.2 on 2026-10-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsectionitem',
            name='listing_unit_id',
            field=models.PositiveIntegerField(blank=True, help_text='ListingUnit.id from Product app — selected from existing refurbisher listings', null=True),
        ),
        migrations.AddField(
            model_name='spotlightproduct',
            name='listing_unit_id',
            field=models.PositiveIntegerField(blank=True, help_text='ListingUnit.id from Product app — selected from existing refurbisher listings', null=True),
        ),
        migrations.AlterField(
            model_name='productsectionitem',
            name='product_model_id',
            field=models.PositiveIntegerField(blank=True, help_text='ProductModel.id from Product app', null=True),
        ),
        migrations.AlterField(
            model_name='spotlightproduct',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='spotlightproduct',
            name='product_model_id',
            field=models.PositiveIntegerField(blank=True, help_text='ProductModel.id', null=True),
        ),
    ]
