# Generated by Django 5.1.2 on 2026-10-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_productsectionitem_listing_unit_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSectionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('categories', 'Shop by Category'), ('spotlight', "Today's Spotlight"), ('price_range', 'Find Your Price Range'), ('shop_by_price', 'Shop by Price'), ('testimonials', 'Testimonials'), ('faq', 'Frequently Asked Questions')], max_length=30, unique=True)),
                ('eyebrow', models.CharField(blank=True, help_text='Small label above the heading', max_length=120)),
                ('heading', models.CharField(max_length=200)),
                ('subheading', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide the whole section')),
            ],
            options={
                'verbose_name': 'Homepage Section Heading',
            },
        ),
        migrations.AddField(
            model_name='productsection',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional line shown under the heading', max_length=200),
        ),
    ]
