# Generated by Django 5.1.2 on 2026-01-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_rename_shipping_charge_order_delivery_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='device_imei',
            field=models.CharField(blank=True, help_text='IMEI or identification number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='device_photos',
            field=models.JSONField(blank=True, default=list, help_text='List of device photo URLs'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('device_verified', 'Device Verified'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='packed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Notes from refurbisher during verification', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
