# Generated by Django 5.1.2 on 2026-01-21 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_orderitem_device_imei_orderitem_device_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='device_photos',
        ),
        migrations.CreateModel(
            name='DevicePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Device verification photo', upload_to='device_photos/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_photos', to='Order.orderitem')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
