# Generated by Django 5.1.2 on 2026-01-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_remove_orderitem_device_photos_devicephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='refurbisher_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
