# Generated by Django 5.1.2 on 2026-08-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_alter_orderitem_refurbisher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text="Auto-stamped the first time status becomes 'delivered'; drives the return-eligibility window", null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='warranty_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of extended warranty prices for order items that opted in', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='has_extended_warranty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_status',
            field=models.CharField(choices=[('none', 'No Return'), ('requested', 'Return Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='warranty_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
