# Generated by Django 5.1.2 on 2026-09-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_order_courier_name_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='box_breadth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='box_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='box_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='box_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pickup_scheduled_date',
            field=models.DateField(blank=True, help_text='Date refurbisher wants ShipRocket to pick up this item', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipping_selected_at',
            field=models.DateTimeField(blank=True, help_text='When the refurbisher confirmed pickup time + courier', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shiprocket_awb_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shiprocket_courier_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shiprocket_courier_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shiprocket_last_error',
            field=models.TextField(blank=True, help_text='Last error encountered while talking to ShipRocket, if any', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shiprocket_last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shiprocket_order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shiprocket_shipment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shiprocket_shipping_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shiprocket_status',
            field=models.CharField(blank=True, help_text='Latest raw status text from ShipRocket', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shiprocket_tracking_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
