# Generated by Django 5.1.2 on 2026-10-07 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_orderitem_box_breadth_orderitem_box_height_and_more'),
        ('Product', '0013_commissionconfig_listingunit_commission_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='listing_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='Product.listingunit'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'listing_unit'), name='unique_unit_per_order'),
        ),
    ]
