# Generated by Django 5.1 on 2025-11-04 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0005_remove_listing_condition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('session_id', models.CharField(blank=True, help_text='Session ID for guest users (CSRF token)', max_length=255, null=True)),
                ('active_cart', models.BooleanField(default=True, help_text='Only one active cart per user/session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='User for authenticated carts', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ShoppingCart.shoppingcart')),
                ('listing_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='Product.listingunit')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shoppingcart',
            index=models.Index(fields=['session_id', 'active_cart'], name='ShoppingCar_session_c707e8_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppingcart',
            index=models.Index(fields=['user', 'active_cart'], name='ShoppingCar_user_id_be45cf_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppingcartitem',
            index=models.Index(fields=['cart', 'listing_unit'], name='ShoppingCar_cart_id_4aeafd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcartitem',
            unique_together={('cart', 'listing_unit')},
        ),
    ]
