# Generated by Django 5.1.2 on 2026-08-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingCart', '0002_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartitem',
            name='has_extended_warranty',
            field=models.BooleanField(default=False, help_text='Whether the customer opted into extended warranty for this unit'),
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='warranty_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Server-computed warranty price snapshot, based on the listing's category", max_digits=10),
        ),
    ]
