# Generated by Django 5.1 on 2025-10-16 22:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributemaster',
            options={'ordering': ['category', 'display_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='listingunit',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['brand', 'name']},
        ),
        migrations.RemoveIndex(
            model_name='listingunitattribute',
            name='Product_lis_attribu_b1104e_idx',
        ),
        migrations.RemoveField(
            model_name='listingunit',
            name='image',
        ),
        migrations.RemoveField(
            model_name='listingunit',
            name='imei_number',
        ),
        migrations.RemoveField(
            model_name='listingunit',
            name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='productmodel',
            unique_together={('brand', 'name', 'category')},
        ),
        migrations.AddField(
            model_name='attributemaster',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attributemaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_id',
            field=models.CharField(default='', editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodelattribute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attributemaster',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('laptop', 'Laptop'), ('accessory', 'Accessory')], max_length=20),
        ),
        migrations.AlterField(
            model_name='attributemaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attributemaster',
            name='data_type',
            field=models.CharField(choices=[('text', 'Text'), ('choice', 'Choice'), ('number', 'Number')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='attributemaster',
            name='possible_values',
            field=models.JSONField(blank=True, default=list, help_text='List of possible values for choice type attributes'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('sold', 'Sold'), ('inactive', 'Inactive')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='total_quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='listingunit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listingunit',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='listingunitattribute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listingunitattribute',
            name='value',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('laptop', 'Laptop'), ('accessory', 'Accessory')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productmodelattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_models', to='Product.attributemaster'),
        ),
        migrations.AlterField(
            model_name='productmodelattribute',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productmodelattribute',
            name='product_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_attributes', to='Product.productmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='listingunitattribute',
            unique_together={('listing_unit', 'attribute')},
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='base_specs',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='updated_at',
        ),
    ]
