# Generated by Django 5.1 on 2025-10-17 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_attributemaster_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingunit',
            options={'ordering': ['unit_number']},
        ),
        migrations.AddField(
            model_name='listingunit',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listingunit',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingunit',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='listingunit',
            name='unit_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='listingunit',
            unique_together={('listing', 'unit_number')},
        ),
    ]
