# Generated by Django 5.1 on 2025-10-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_listingunit_options_listingunit_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingunit',
            name='unit_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
