# Generated by Django 5.1 on 2025-10-17 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_listingunit_unit_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='listingunit',
            name='quantity',
        ),
        migrations.AddField(
            model_name='listingunit',
            name='condition',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='excellent', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listingunit',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1200, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
