# Generated by Django 5.1.2 on 2025-11-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_remove_listing_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingunit',
            name='half_sold',
            field=models.BooleanField(default=False, help_text='Temporarily held during checkout'),
        ),
        migrations.AddField(
            model_name='listingunit',
            name='half_sold_at',
            field=models.DateTimeField(blank=True, help_text='When product was marked as half sold', null=True),
        ),
    ]
