# Generated by Django 5.1.2 on 2026-02-06 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_listingunit_half_sold_listingunit_half_sold_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_models/')),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Product.productmodel')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
