# Generated by Django 5.1.2 on 2026-02-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_productmodelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodelattribute',
            name='is_filter',
            field=models.BooleanField(default=True, verbose_name='Customer side should it be filterable'),
        ),
    ]
