# Generated by Django 5.1.2 on 2026-02-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_productmodelattribute_is_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('sold', 'Sold'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
