# Generated by Django 5.1.2 on 2026-07-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_alter_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodelattribute',
            name='section',
            field=models.CharField(choices=[('main', 'Main'), ('secondary', 'Secondary')], default='main', help_text='Which section of the product detail page this attribute appears in', max_length=20),
        ),
    ]
