# Generated by Django 5.1.2 on 2026-07-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_productmodelattribute_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributemaster',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='attributemaster',
            name='possible_values',
        ),
        migrations.AddField(
            model_name='productmodelattribute',
            name='data_type',
            field=models.CharField(choices=[('text', 'Text'), ('choice', 'Choice'), ('number', 'Number')], default='text', help_text='Input type for this attribute on this product', max_length=20),
        ),
        migrations.AddField(
            model_name='productmodelattribute',
            name='possible_values',
            field=models.JSONField(blank=True, default=list, help_text="Allowed values when data_type is 'choice'"),
        ),
    ]
