# Generated by Django 5.1.2 on 2026-08-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_remove_attributemaster_data_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Guide/reference refurb price range (upper bound) — extracted from catalog data. Refurbishers still set their own unit price.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Guide/reference refurb price range (lower bound) — extracted from catalog data. Refurbishers still set their own unit price.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productmodelattribute',
            name='default_value',
            field=models.CharField(blank=True, help_text="Fixed spec value for this attribute on this product (e.g. Processor, Screen Size). Only used when is_required is False — the refurbisher is not asked for it, and it is auto-copied onto every unit of this model's listings.", max_length=200, null=True),
        ),
    ]
