# Generated by Django 5.1.2 on 2026-10-06 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_productmodel_price_max_productmodel_price_min_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, unique=True)),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat amount')], default='percentage', max_length=12)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.AddField(
            model_name='listingunit',
            name='commission_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('flat', 'Flat amount')], help_text='Per-unit override. Leave empty to use the category default.', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='listingunit',
            name='commission_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Per-unit override value (percent or flat amount)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='listingunit',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform commission amount added on top of the refurbisher price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='listingunit',
            name='refurbisher_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price set by the refurbisher (what they earn)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='listingunit',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Customer-facing price = refurbisher_price + platform_commission', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
