"""
Order/invoice.py
----------------
Invoice PDF generation for Recarvit orders.
GET  /api/orders/invoice/<order_id>/

Requires: pip install reportlab
Logo  : static/images/new logo/Recarvit Logo edited-nobg.png
        (also accepted at Order/static/images/logo.png as fallback)
"""

import os
from io import BytesIO
from decimal import Decimal

from django.http import HttpResponse
from django.conf import settings
from django.shortcuts import get_object_or_404

from rest_framework.views import APIView

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_RIGHT, TA_CENTER
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, Image as RLImage
)
from reportlab.graphics.shapes import Drawing, Rect
from reportlab.pdfgen import canvas

from Order.models import Order, OrderItem

# ---------------------------------------------------------------------------
# Brand colours
# ---------------------------------------------------------------------------
GREEN       = colors.HexColor("#2E7D32")
LIGHT_GREEN = colors.HexColor("#E8F5E9")
DARK_GRAY   = colors.HexColor("#212121")
MID_GRAY    = colors.HexColor("#616161")
LIGHT_GRAY  = colors.HexColor("#F5F5F5")
WHITE       = colors.white
BLACK       = colors.black

PAGE_W, PAGE_H = A4
MARGIN = 15 * mm

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _fmt_inr(value):
    """Format Decimal/float as ₹1,23,456.00"""
    try:
        v = float(value)
    except (TypeError, ValueError):
        return "₹0.00"
    # Indian number formatting
    s = f"{v:,.2f}"
    # Convert Western grouping to Indian grouping
    parts = s.split(".")
    integer = parts[0].replace(",", "")
    dec = parts[1]
    if len(integer) > 3:
        last3 = integer[-3:]
        rest = integer[:-3]
        groups = []
        while len(rest) > 2:
            groups.insert(0, rest[-2:])
            rest = rest[:-2]
        if rest:
            groups.insert(0, rest)
        integer = ",".join(groups) + "," + last3
    return f"₹{integer}.{dec}"


def _logo_path():
    """Return absolute path to the Recarvit logo, trying multiple locations."""
    candidates = [
        os.path.join(settings.BASE_DIR, "static", "images", "new logo", "Recarvit Logo edited-nobg.png"),
        os.path.join(settings.BASE_DIR, "static", "images", "logo.png"),
        os.path.join(os.path.dirname(__file__), "static", "images", "logo.png"),
    ]
    for p in candidates:
        if os.path.exists(p):
            return p
    return None


def _get_company_profile(refurbisher_user):
    """Safely fetch CompanyProfile for a refurbisher."""
    return getattr(refurbisher_user, "company_profile", None)


# ---------------------------------------------------------------------------
# PDF canvas callback – page numbers + border
# ---------------------------------------------------------------------------

class _NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        total = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self._draw_page(total)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def _draw_page(self, total):
        self.saveState()
        # Thin green border
        self.setStrokeColor(GREEN)
        self.setLineWidth(1.2)
        self.rect(MARGIN * 0.6, MARGIN * 0.6,
                  PAGE_W - MARGIN * 1.2, PAGE_H - MARGIN * 1.2)
        # Footer
        self.setFillColor(MID_GRAY)
        self.setFont("Helvetica", 7.5)
        footer = f"Page {self._pageNumber} of {total}  |  Generated by Recarvit – recarvit.com  |  Tax included in item prices"
        self.drawCentredString(PAGE_W / 2, MARGIN * 0.5, footer)
        self.restoreState()


# ---------------------------------------------------------------------------
# Main view
# ---------------------------------------------------------------------------

class InvoiceView(APIView):
    """
    GET /api/orders/invoice/<order_id>/
    Returns a downloadable PDF invoice for the given order.
    Accessible without authentication (order_id acts as the token).
    """

    def get(self, request, order_id):
        order = get_object_or_404(Order, order_id=order_id)
        pdf_bytes = self._build_pdf(order, request)

        filename = f"Recarvit_Invoice_{order.order_id}.pdf"
        response = HttpResponse(pdf_bytes, content_type="application/pdf")
        response["Content-Disposition"] = f'attachment; filename="{filename}"'
        return response

    # ------------------------------------------------------------------
    # PDF builder
    # ------------------------------------------------------------------

    def _build_pdf(self, order: Order, request) -> bytes:
        buf = BytesIO()
        doc = SimpleDocTemplate(
            buf,
            pagesize=A4,
            leftMargin=MARGIN,
            rightMargin=MARGIN,
            topMargin=MARGIN,
            bottomMargin=MARGIN + 6 * mm,
            title=f"Invoice – {order.order_id}",
            author="Recarvit",
        )

        styles = getSampleStyleSheet()
        story = []

        # ── Header ────────────────────────────────────────────────────
        story += self._header_section(order)
        story.append(Spacer(1, 4 * mm))
        story.append(HRFlowable(width="100%", thickness=1, color=GREEN, spaceAfter=4 * mm))

        # ── Billing & Shipping addresses ──────────────────────────────
        story += self._address_section(order)
        story.append(Spacer(1, 4 * mm))

        # ── Order meta row ────────────────────────────────────────────
        story += self._order_meta(order)
        story.append(Spacer(1, 5 * mm))

        # ── Items table (grouped by refurbisher) ──────────────────────
        story += self._items_section(order, request)
        story.append(Spacer(1, 5 * mm))

        # ── Price summary ─────────────────────────────────────────────
        story += self._price_summary(order)
        story.append(Spacer(1, 6 * mm))

        # ── GST note ──────────────────────────────────────────────────
        note_style = ParagraphStyle(
            "note", parent=styles["Normal"],
            fontSize=7.5, textColor=MID_GRAY,
            leading=11,
        )
        story.append(Paragraph(
            "* All prices are inclusive of applicable GST. This is a computer-generated invoice and does not require a signature.",
            note_style,
        ))
        story.append(Spacer(1, 3 * mm))
        story.append(HRFlowable(width="100%", thickness=0.5, color=LIGHT_GRAY, spaceAfter=3 * mm))
        story.append(Paragraph(
            "Thank you for choosing Recarvit – Certified Refurbished Electronics | recarvit.com",
            ParagraphStyle("thanks", parent=styles["Normal"],
                           fontSize=8, textColor=GREEN, alignment=TA_CENTER, leading=12),
        ))

        doc.build(story, canvasmaker=_NumberedCanvas)
        return buf.getvalue()

    # ------------------------------------------------------------------
    # Section builders
    # ------------------------------------------------------------------

    def _header_section(self, order: Order):
        styles = getSampleStyleSheet()

        logo_path = _logo_path()
        if logo_path:
            logo = RLImage(logo_path, width=42 * mm, height=14 * mm, kind="proportional")
        else:
            logo = Paragraph(
                '<font color="#2E7D32" size="16"><b>recarvit</b></font>',
                ParagraphStyle("logo_text", parent=styles["Normal"], fontSize=16,
                               textColor=GREEN, leading=18),
            )

        title_style = ParagraphStyle(
            "inv_title", parent=styles["Normal"],
            fontSize=18, textColor=DARK_GRAY, leading=22,
            alignment=TA_RIGHT, fontName="Helvetica-Bold",
        )
        meta_style = ParagraphStyle(
            "inv_meta", parent=styles["Normal"],
            fontSize=8.5, textColor=MID_GRAY, leading=13, alignment=TA_RIGHT,
        )

        inv_number = order.order_number or order.order_id
        right_block = [
            Paragraph("TAX INVOICE", title_style),
            Paragraph(f"Invoice No: <b>{inv_number}</b>", meta_style),
            Paragraph(f"Order ID: {order.order_id}", meta_style),
            Paragraph(f"Date: {order.created_at.strftime('%d %b %Y')}", meta_style),
            Paragraph(
                f"Status: <font color='{'#2E7D32' if order.status == 'delivered' else '#F57C00'}'>"
                f"<b>{order.get_status_display()}</b></font>",
                meta_style,
            ),
        ]

        data = [[logo, right_block]]
        t = Table(data, colWidths=[PAGE_W * 0.45 - MARGIN, PAGE_W * 0.55 - MARGIN])
        t.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("ALIGN",  (1, 0), (1, 0),  "RIGHT"),
        ]))
        return [t]

    def _address_section(self, order: Order):
        styles = getSampleStyleSheet()
        head_style = ParagraphStyle(
            "addr_head", parent=styles["Normal"],
            fontSize=8, textColor=GREEN, leading=11,
            fontName="Helvetica-Bold", spaceAfter=2,
        )
        body_style = ParagraphStyle(
            "addr_body", parent=styles["Normal"],
            fontSize=8.5, textColor=DARK_GRAY, leading=13,
        )

        # Bill-to (customer)
        bill_name = f"{order.first_name} {order.last_name}"
        if order.different_billing_address and order.billing_address:
            bill_addr = order.billing_address
            bill_city_state = f"{order.billing_city}, {order.billing_state} – {order.billing_pincode}"
            bill_phone = order.billing_phone or order.phone
        else:
            bill_addr = order.shipping_address
            bill_city_state = f"{order.shipping_city}, {order.shipping_state} – {order.shipping_pincode}"
            bill_phone = order.phone

        bill_col = [
            Paragraph("BILL TO", head_style),
            Paragraph(f"<b>{bill_name}</b>", body_style),
            Paragraph(bill_addr, body_style),
            Paragraph(bill_city_state, body_style),
            Paragraph(f"Phone: {bill_phone}", body_style),
            Paragraph(f"Email: {order.email}", body_style),
        ]

        # Ship-to
        ship_col = [
            Paragraph("SHIP TO", head_style),
            Paragraph(f"<b>{order.first_name} {order.last_name}</b>", body_style),
            Paragraph(order.shipping_address, body_style),
            Paragraph(
                f"{order.shipping_city}, {order.shipping_state} – {order.shipping_pincode}",
                body_style,
            ),
            Paragraph(f"Phone: {order.phone}", body_style),
        ]
        if order.special_instructions:
            ship_col.append(Paragraph(f"Note: {order.special_instructions}", body_style))

        col_w = (PAGE_W - MARGIN * 2) / 2 - 3 * mm
        t = Table([[bill_col, ship_col]], colWidths=[col_w, col_w])
        t.setStyle(TableStyle([
            ("VALIGN",      (0, 0), (-1, -1), "TOP"),
            ("BACKGROUND",  (0, 0), (0, 0),   LIGHT_GREEN),
            ("BACKGROUND",  (1, 0), (1, 0),   LIGHT_GRAY),
            ("BOX",         (0, 0), (0, 0),   0.5, GREEN),
            ("BOX",         (1, 0), (1, 0),   0.5, colors.HexColor("#E0E0E0")),
            ("LEFTPADDING",  (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING",   (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING",(0, 0), (-1, -1), 6),
            ("ROUNDEDCORNERS", (0, 0), (-1, -1), [3]),
        ]))
        return [t]

    def _order_meta(self, order: Order):
        styles = getSampleStyleSheet()
        cell_style = ParagraphStyle(
            "meta_cell", parent=styles["Normal"],
            fontSize=8.5, leading=13, alignment=TA_CENTER,
        )
        label_style = ParagraphStyle(
            "meta_label", parent=styles["Normal"],
            fontSize=7.5, textColor=MID_GRAY, leading=11,
            alignment=TA_CENTER,
        )

        payment_label = order.get_payment_method_display()
        payment_received = "Received" if order.payment_received else "Pending"

        cells = [
            [Paragraph("Order Date", label_style),
             Paragraph("Payment Method", label_style),
             Paragraph("Payment Status", label_style),
             Paragraph("Delivery Charge", label_style),
             Paragraph("Total Amount", label_style)],
            [Paragraph(f"<b>{order.created_at.strftime('%d %b %Y')}</b>", cell_style),
             Paragraph(f"<b>{payment_label}</b>", cell_style),
             Paragraph(
                 f"<font color='{'#2E7D32' if order.payment_received else '#C62828'}'>"
                 f"<b>{payment_received}</b></font>",
                 cell_style,
             ),
             Paragraph(f"<b>{_fmt_inr(order.delivery_charge)}</b>", cell_style),
             Paragraph(
                 f"<font color='#2E7D32'><b>{_fmt_inr(order.total_amount)}</b></font>",
                 cell_style,
             )],
        ]

        col_w = (PAGE_W - MARGIN * 2) / 5
        t = Table(cells, colWidths=[col_w] * 5)
        t.setStyle(TableStyle([
            ("BACKGROUND",   (0, 0), (-1, 0), LIGHT_GREEN),
            ("BACKGROUND",   (0, 1), (-1, 1), WHITE),
            ("BOX",          (0, 0), (-1, -1), 0.5, GREEN),
            ("INNERGRID",    (0, 0), (-1, -1), 0.3, colors.HexColor("#C8E6C9")),
            ("TOPPADDING",   (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
            ("VALIGN",       (0, 0), (-1, -1), "MIDDLE"),
        ]))
        return [t]

    def _items_section(self, order: Order, request):
        styles = getSampleStyleSheet()
        story = []

        heading_style = ParagraphStyle(
            "section_head", parent=styles["Normal"],
            fontSize=10, fontName="Helvetica-Bold",
            textColor=WHITE, leading=14,
        )
        seller_head_style = ParagraphStyle(
            "seller_head", parent=styles["Normal"],
            fontSize=8.5, fontName="Helvetica-Bold",
            textColor=DARK_GRAY, leading=13,
        )
        seller_body_style = ParagraphStyle(
            "seller_body", parent=styles["Normal"],
            fontSize=8, textColor=MID_GRAY, leading=12,
        )
        cell_style = ParagraphStyle(
            "tbl_cell", parent=styles["Normal"],
            fontSize=8.5, textColor=DARK_GRAY, leading=13,
        )
        header_cell_style = ParagraphStyle(
            "tbl_hdr", parent=styles["Normal"],
            fontSize=8.5, fontName="Helvetica-Bold",
            textColor=WHITE, leading=13, alignment=TA_CENTER,
        )
        right_cell_style = ParagraphStyle(
            "tbl_right", parent=styles["Normal"],
            fontSize=8.5, textColor=DARK_GRAY, leading=13, alignment=TA_RIGHT,
        )

        # Section heading bar
        heading_tbl = Table(
            [[Paragraph("ORDER ITEMS", heading_style)]],
            colWidths=[PAGE_W - MARGIN * 2],
        )
        heading_tbl.setStyle(TableStyle([
            ("BACKGROUND",  (0, 0), (-1, -1), GREEN),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING",  (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
        ]))
        story.append(heading_tbl)
        story.append(Spacer(1, 2 * mm))

        # Group items by refurbisher
        items_by_seller = {}
        for item in order.items.select_related(
            "listing_unit__listing__model__brand",
            "refurbisher",
        ).all():
            rid = item.refurbisher_id
            if rid not in items_by_seller:
                items_by_seller[rid] = {"refurbisher": item.refurbisher, "items": []}
            items_by_seller[rid]["items"].append(item)

        total_w = PAGE_W - MARGIN * 2
        col_widths = [8 * mm, total_w * 0.42, 28 * mm, 16 * mm, 28 * mm]

        for seller_group in items_by_seller.values():
            refurbisher = seller_group["refurbisher"]
            cp = _get_company_profile(refurbisher)

            # Seller info block
            if cp:
                company_name = cp.company_name or f"{refurbisher.first_name} {refurbisher.last_name}"
                gst = cp.gst_registration_no or "N/A"
                addr_parts = filter(None, [
                    cp.address_line_1, cp.address_line_2,
                    cp.city, cp.state, cp.pincode,
                ])
                seller_addr = ", ".join(addr_parts) or "Address not provided"
                seller_email = cp.email or ""
                seller_phone = cp.contact_number or ""
            else:
                company_name = item.refurbisher_name or f"{refurbisher.first_name} {refurbisher.last_name}"
                gst = "N/A"
                seller_addr = "Address not provided"
                seller_email = ""
                seller_phone = ""

            seller_detail_left = [
                Paragraph(f"Sold By: <b>{company_name}</b>", seller_head_style),
                Paragraph(f"GST No: {gst}", seller_body_style),
            ]
            seller_detail_right = [
                Paragraph(seller_addr, seller_body_style),
            ]
            if seller_email:
                seller_detail_right.append(Paragraph(f"Email: {seller_email}", seller_body_style))
            if seller_phone:
                seller_detail_right.append(Paragraph(f"Phone: {seller_phone}", seller_body_style))

            half_w = total_w / 2
            seller_tbl = Table(
                [[seller_detail_left, seller_detail_right]],
                colWidths=[half_w, half_w],
            )
            seller_tbl.setStyle(TableStyle([
                ("BACKGROUND",   (0, 0), (-1, -1), LIGHT_GREEN),
                ("BOX",          (0, 0), (-1, -1), 0.5, GREEN),
                ("LEFTPADDING",  (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING",   (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
                ("VALIGN",       (0, 0), (-1, -1), "TOP"),
            ]))
            story.append(seller_tbl)
            story.append(Spacer(1, 1.5 * mm))

            # Table header
            header_row = [
                Paragraph("#",        header_cell_style),
                Paragraph("Product",  header_cell_style),
                Paragraph("Price",    header_cell_style),
                Paragraph("Qty",      header_cell_style),
                Paragraph("Total",    header_cell_style),
            ]

            rows = [header_row]
            for idx, item in enumerate(seller_group["items"], 1):
                lu = item.listing_unit
                listing = lu.listing
                model   = listing.model
                brand   = model.brand.name

                # Build product description
                product_name = f"{brand} {model.name}"
                condition = item.condition_at_purchase.title()
                attrs = lu.attributes.select_related("attribute").all()
                main_attrs = [
                    f"{a.attribute.name}: {a.value}"
                    for a in attrs
                    if hasattr(a.attribute, "section") and a.attribute.section == "main"
                ][:4]
                attr_str = "  |  ".join(main_attrs) if main_attrs else ""
                imei_str = f"IMEI: {item.device_imei}" if item.device_imei else ""

                desc_lines = [f"<b>{product_name}</b>"]
                if attr_str:
                    desc_lines.append(f'<font size="7.5" color="#757575">{attr_str}</font>')
                desc_lines.append(
                    f'<font size="7.5" color="#2E7D32">Condition: {condition}</font>'
                    + (f'  <font size="7.5" color="#757575">{imei_str}</font>' if imei_str else "")
                )

                desc_para = Paragraph("<br/>".join(desc_lines), cell_style)

                rows.append([
                    Paragraph(str(idx), ParagraphStyle(
                        "center_cell", parent=cell_style, alignment=TA_CENTER)),
                    desc_para,
                    Paragraph(_fmt_inr(item.price_at_purchase), right_cell_style),
                    Paragraph("1", ParagraphStyle(
                        "center_cell2", parent=cell_style, alignment=TA_CENTER)),
                    Paragraph(_fmt_inr(item.price_at_purchase), right_cell_style),
                ])

            items_tbl = Table(rows, colWidths=col_widths)
            items_tbl.setStyle(TableStyle([
                # Header row
                ("BACKGROUND",   (0, 0), (-1, 0), DARK_GRAY),
                ("TEXTCOLOR",    (0, 0), (-1, 0), WHITE),
                # Alternating rows
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_GRAY]),
                # Grid
                ("BOX",          (0, 0), (-1, -1), 0.5, colors.HexColor("#BDBDBD")),
                ("LINEBELOW",    (0, 0), (-1, 0),  0.5, GREEN),
                ("INNERGRID",    (0, 1), (-1, -1), 0.3, colors.HexColor("#E0E0E0")),
                # Padding
                ("LEFTPADDING",  (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING",   (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
                ("VALIGN",       (0, 0), (-1, -1), "MIDDLE"),
                ("ALIGN",        (0, 0), (0, -1),  "CENTER"),
                ("ALIGN",        (2, 0), (2, -1),  "RIGHT"),
                ("ALIGN",        (3, 0), (3, -1),  "CENTER"),
                ("ALIGN",        (4, 0), (4, -1),  "RIGHT"),
            ]))
            story.append(items_tbl)
            story.append(Spacer(1, 3 * mm))

        return story

    def _price_summary(self, order: Order):
        styles = getSampleStyleSheet()
        story = []

        label_style = ParagraphStyle(
            "sum_label", parent=styles["Normal"],
            fontSize=9, textColor=DARK_GRAY, leading=14,
        )
        value_style = ParagraphStyle(
            "sum_value", parent=styles["Normal"],
            fontSize=9, textColor=DARK_GRAY, leading=14, alignment=TA_RIGHT,
        )
        total_label_style = ParagraphStyle(
            "total_label", parent=styles["Normal"],
            fontSize=10, fontName="Helvetica-Bold",
            textColor=WHITE, leading=15,
        )
        total_value_style = ParagraphStyle(
            "total_value", parent=styles["Normal"],
            fontSize=10, fontName="Helvetica-Bold",
            textColor=WHITE, leading=15, alignment=TA_RIGHT,
        )
        green_value_style = ParagraphStyle(
            "green_val", parent=styles["Normal"],
            fontSize=9, textColor=GREEN, leading=14,
            alignment=TA_RIGHT, fontName="Helvetica-Bold",
        )
        gst_note_style = ParagraphStyle(
            "gst_note", parent=styles["Normal"],
            fontSize=7.5, textColor=MID_GRAY, leading=11,
        )

        subtotal  = Decimal(str(order.subtotal_amount))
        tax       = Decimal(str(order.tax_amount))
        delivery  = Decimal(str(order.delivery_charge))
        discount  = Decimal(str(order.discount_amount))
        coupon_d  = Decimal(str(order.coupon_discount))
        total     = Decimal(str(order.total_amount))

        # GST breakdown (18% included in price — back-calculate)
        gst_rate   = Decimal("0.18")
        gst_amount = (subtotal * gst_rate / (1 + gst_rate)).quantize(Decimal("0.01"))
        base_price = subtotal - gst_amount

        total_savings = discount + coupon_d
        if delivery == 0:
            delivery_display = Paragraph(
                '<font color="#2E7D32"><b>FREE</b></font>', value_style)
        else:
            delivery_display = Paragraph(_fmt_inr(delivery), value_style)

        # Right-align the summary table
        summary_rows = [
            [Paragraph("Price (excl. GST)", label_style),
             Paragraph(_fmt_inr(base_price), value_style)],
            [Paragraph("GST (18% incl.)", label_style),
             Paragraph(_fmt_inr(gst_amount), value_style)],
        ]
        if discount > 0:
            summary_rows.append([
                Paragraph("Discount", label_style),
                Paragraph(f'<font color="#2E7D32">− {_fmt_inr(discount)}</font>', value_style),
            ])
        if coupon_d > 0:
            summary_rows.append([
                Paragraph(f"Coupon ({order.coupon_code or ''})", label_style),
                Paragraph(f'<font color="#2E7D32">− {_fmt_inr(coupon_d)}</font>', value_style),
            ])
        summary_rows.append([
            Paragraph("Delivery Charges", label_style),
            delivery_display,
        ])

        # Totals row
        total_row = [
            Paragraph("GRAND TOTAL", total_label_style),
            Paragraph(_fmt_inr(total), total_value_style),
        ]

        # Spacer row
        def _spacer_row():
            return [Paragraph("", label_style), Paragraph("", value_style)]

        summary_rows.append(_spacer_row())
        summary_rows.append(total_row)

        total_w   = PAGE_W - MARGIN * 2
        left_pad  = total_w * 0.55
        right_pad = total_w * 0.45

        tbl = Table(summary_rows, colWidths=[right_pad * 0.62, right_pad * 0.38])
        row_styles = [
            ("BOX",          (0, 0), (-1, -2), 0.5, colors.HexColor("#BDBDBD")),
            ("INNERGRID",    (0, 0), (-1, -2), 0.3, colors.HexColor("#E8E8E8")),
            ("BACKGROUND",   (0, 0), (-1, -2), LIGHT_GRAY),
            ("ROWBACKGROUNDS",(0, 0), (-1, -2), [WHITE, LIGHT_GRAY]),
            # Grand total row
            ("BACKGROUND",   (0, -1), (-1, -1), DARK_GRAY),
            ("BOX",          (0, -1), (-1, -1), 1, GREEN),
            # Spacer row (second to last) transparent
            ("BACKGROUND",   (0, -2), (-1, -2), WHITE),
            ("LINEABOVE",    (0, -1), (-1, -1), 1.5, GREEN),
            # Padding
            ("LEFTPADDING",  (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ("TOPPADDING",   (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
            ("VALIGN",       (0, 0), (-1, -1), "MIDDLE"),
            ("ALIGN",        (1, 0), (1, -1),  "RIGHT"),
        ]
        tbl.setStyle(TableStyle(row_styles))

        # Wrap in right-aligned outer table
        outer = Table([[Paragraph("", label_style), tbl]],
                      colWidths=[left_pad, right_pad])
        outer.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(outer)

        # Savings pill (if any)
        if total_savings > 0:
            savings_para = Paragraph(
                f'<font color="#2E7D32"><b>You saved {_fmt_inr(total_savings)} on this order!</b></font>',
                ParagraphStyle("savings", parent=styles["Normal"],
                               fontSize=8.5, alignment=TA_RIGHT, leading=13),
            )
            story.append(savings_para)

        return story
